# Generated by Django 3.1.6 on 2021-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='No desc. provided', max_length=1000)),
                ('is_completed', models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], default='NO', max_length=3)),
            ],
        ),
    ]
