# Generated by Django 3.1.6 on 2021-03-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210319_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='No image provided', upload_to='myapp/static/myapp/uploads/'),
        ),
    ]
