# Generated by Django 3.1.6 on 2021-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210322_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='No image provided', upload_to='static/myapp/images'),
        ),
    ]
